src/book/urls.py
from django.urls import path, re_path

from . import views

app_name = 'book'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.BookListView.as_view(), name='bookList'),
    path('detail/<int:pk>/', views.BookDetailView.as_view(), name='bookDetail'),
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name='myBooks'),
    path('borrowed/', views.LoanedBookListView.as_view(), name='allBorrowed'),
    path('<int:pk>/renew/', views.renew_book_librarian,
         name='renewBookLibrarian'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Addresses added here

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

src/book/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

import uuid


# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(max_length=13, help_text='13 charecter')
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this Book')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)


class BookInstance(models.Model):
    id = models.AutoField(primary_key=True)
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (
            ("librarian", "librarian"),
        )

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.book.title)

src/book/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        return data

src/book/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from datetime import datetime, date, timedelta
from book.forms import RenewBookForm

from .models import Author
from .models import Book
from .models import BookInstance
from .models import Genre
# Create your views here.


@login_required
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()
    num_author = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_author': num_author,
    }
    return render(request, 'book/index.html', context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 3

    redirect_fiels_name = ''

    '''
    #login_url = 'accounts/login/'
    #template_name = "book_list.html"
    #context_object_name = "book_list"
    #query = Book.objects.filter(title__icontains='django')[:5]

    def get_queryset(self):
        return Book.objects.filter(title__icontains='farm')[:5]

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)

        context['my_book_list'] = Book.objects.all()

        return context
    '''


class LoanedBookListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'book/borrowed_list.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book
    template_name = "book/book_detail.html"

    redirect_fiels_name = ''


'''
    login_url = 'accounts/login/'
def book_detail_view(request, pk):
    try:
        book_id = Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404('Book does not exist.')
    #book_id = get.object_or_404(Book, pk = pk)

    return render(request, 'book/book_detail.html', context={'book': book_id})
'''


class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'book/bookinstance_list_borrower_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('book.librarian')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':

        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse_lazy('book:allBorrowed'))

    else:
        proposed_renewal_date = date.today() + timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'book/book_renew_librarian.html', context)

src/media/templates/book/book_detail.html
{% extends "../shared/main.html" %}

{% block title %}
    {{ super }}| Book | Detail
{% endblock title %}

{% block body %}
<div class="container">
  <div class="row mt-5">
    <div class="col-md-6 left-div">
      <div class="starter-template">
        <h1>Books Detail</h1>
        <hr>
        <ul class="list-unstyled">
            <li>
                <p><strong>Title: </strong>{{ book.title }}</p>
            </li>
            <li>
                <p><strong>Summary: </strong>{{ book.summary }}</p>
            </li>
            <li>
                <p><strong>ISBN: </strong>{{ book.isbn }}</p>
            </li>
            <li>
                <p>
                    <strong>Instances: </strong>
                    <br>
                    <ul>
                        {% for copy in book.bookinstance_set.all %}
                            <li><p><strong>Status: </strong>{{ copy.status }}</p></li>
                            <li><p><strong>Imprint: </strong>{{ copy.imprint }}</p></li>
                            <li><p><strong>ID: </strong>{{ copy.id }}</p></li>
                            {% if copy.status == 'o' %}
                                <li><p><strong>Due Back: </strong>{{ copy.due_back }}</p></li>
                            {% endif %}
                            <br>
                        {% endfor %}
                    </ul>
                </p>
            </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      {% include "../partial/carousel.html" %}
    </div>
  </div>
</div>
{% endblock body %}




<h3>Title: {{ book.title }}</h3>
<p>ISBN: {{ book.isbn }}</p>
<hr>
<p>Summary</p>
<br>
{{ book.summary }}
<br>

src/media/templates/book/book_list.html
{% extends '../shared/main.html' %}
{% block title %}
    {{ super }}| Book | list
{% endblock title %}
{% block body %}
  <div class="container">
    <div style="margin-top: 50px;"></div>
      <h1 class="text-center">
        All Books
      </h1>
    </div>
  <div style="margin-bottom: 100px;"></div>

{% if book_list %}
    <div class="table-responsive">
      <table class="table table-hover table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">ISBN</th>
            <th scope="col">Detail</th>
          </tr>
        </thead> 
        <tbody>
        {% for book in book_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ book.title }}</td>
            <td>{{ book.isbn }}</td>
            <td><a class="btn btn-info btn-block" href="{% url 'book:bookDetail' book.id %}">info</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    {% include '../partial/pagination.html' %}

{% else %}
    <h1>Not found!</h1>
{% endif %}
{% endblock body %}

src/media/templates/book/book_renew_librarian.html
{% extends "../shared/main.html" %}
{% block body %}
  <div class="container">
    <div style="margin-top 50px;"></div>
      <h1 class="text-center">
        All Books
      </h1>
    <div style="margin-bottom: 100px;"></div>

    {% if form.errors %}
      {% for error, message in form.errors.items %}
        <div class="alert alert-danger">{{error}} {{message}}</div>
      {% endfor %}
    {% endif %}
    <section class="borrowed" style="background-color:#2c3e50; border-radius:5px; padding: 20px; color:#fff;">
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
        <form method="post">
          {% csrf_token %}
            <div>
              <label for="renewal_date">{{ form.renewal_date.label }}</label>
              {{ form.renewal_date }}
            </div>
          <input class="btn btn-info" type="submit" value="Submit">
        </form>
    </section>
  </div>
{% endblock body %}

src/media/templates/book/bookinstance_list_borrower_user.html
{% extends '../shared/main.html' %}
{% block body %}

<div class="container">
  <div style="margin-top 50px;"></div>
  <div style="margin-bottom: 100px;"></div>
  <section class="borrowed" style="background-color:#2c3e50; border-radius:5px; padding: 20px; color:#fff;">
    <h1 class="text-center text-white">Borrowed Books</h1>
    {% if bookinstance_list %}
      <ul>
        {% for bookinst in bookinstance_list %}
          <li class="{% if bookinst.is_overdue %} text-danger {% else %} text-white {% endif %}">
            <a class="logout-link" href="{% url 'book:bookDetail' bookinst.book.pk %}">{{ bookinst.book.title}}</a> <span>({{ bookinst.due_back }})</span>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-class text-white">There are no books borrowed.</p>
    {% endif %}  
  </section>
</div>
{% endblock body %}

src/media/templates/book/borrowed_list.html
{% extends '../shared/main.html' %}
{% block body %}

<div class="container">
  <div style="margin-top 50px;"></div>
  <div style="margin-bottom: 100px;"></div>
  <section class="borrowed" style="background-color:#2c3e50; border-radius:5px; padding: 20px; color:#fff;">
    <h1 class="text-center text-white">Borrowed Books</h1>
    {% if bookinstance_list %}
      <ul>
        {% for bookinst in bookinstance_list %}
          <li class="{% if bookinst.is_overdue %} text-danger {% else %} text-white {% endif %}">
            <a class="logout-link" href="{% url 'book:renewBookLibrarian' bookinst.id %}">({{ bookinst.due_back }})</a> <span> - {{ bookinst.book.title}} - {{ bookinst.borrower }}</span>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-class text-white">There are no books borrowed.</p>
    {% endif %}  
  </section>
</div>
{% endblock body %}

src/media/templates/book/index.html
{% extends "../shared/main.html" %}

{% block title %}
    {{ super }}| Book | Index
{% endblock title %}

{% block body %}
<div class="container">
  <div class="row mt-5">
    <div class="col-md-6 left-div">
      <div class="starter-template">
        <h1>Home</h1>
        <p class="lead">USC Library Management System</p>
        <hr>
        <ul class="list-unstyled">
            <li>
                <p><strong>Number of books: </strong>{{num_books}}</p>
            </li>
            <li>
                <p><strong>Number of instances: </strong>{{num_instances}}</p>
            </li>
            <li>
                <p><strong>Number of available instances: </strong>{{num_instances_available}}</p>
            </li>
            <li>
                <p><strong>Number of authors: </strong>{{num_author}}</p>
            </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      {% include "../partial/carousel.html" %}
    </div>
  </div>
</div>
{% endblock body %}

src/media/templates/partial/carousel.html
{% load static %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="  border-style: solid;border-width: 20px;border-radius: 20px;">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'img/slider/1.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/slider/2.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/slider/3.jpg' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

src/media/templates/partial/footer.html
<footer>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</footer>

src/media/templates/partial/header.html
<header>   
    
</header>

src/media/templates/partial/navigation.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="https://libraries.usc.edu/">USC Library</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:index' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sections
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'book:bookList' %}">All books</a>
          <a class="dropdown-item" href="{% url 'book:myBooks' %}">My Books</a>
        </div>
      </li>
      {% if perms.book.librarian %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Librarian
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'book:allBorrowed' %}">All borrowed</a>
        </div>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% if user.is_authenticated %}
        <p><a class="btn btn-info" style="margin-right:8px"; href="{% url 'logout' %}">Log Out</a></p>

      {% else %}
        <a href="{% url 'login' %}"><button class="btn btn-info" style="margin-right:8px;">Log in</button></a>
        <a href="#"><button class="btn btn-outline-info">Sign up</button></a>
      {% endif %}
    </form>
  </div>
</nav>

src/media/templates/partial/pagination.html
{% if is_paginated %}
    <nav aria-label="Page Navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li>
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left"></i></a>
          </li>
        {% endif %}

        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item disabled">
              <a class="page-link" href="#">{{ i }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
            </li>         
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li>
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-right"></i></a>
          </li>
        {% endif %}

      </ul>
    </nav>
{% endif %}

src/media/templates/shared/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Library {% block title %}{% endblock title %}</title>
</head>
<body>
  <div style="background-color: hsl(285, 73%, 94%);">
  {% include "../partial/header.html" %}
  {% include "../partial/navigation.html" %}
  <div class="container-fluid">
    {% block body %}
    {% endblock body %}
  </div>
  {% include "../partial/footer.html" %}
  </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>